### ISSUE TITLE
Improvement on structure

### ISSUE THREAD

**Issue by eliseomartelli** [frenck/home-assistant-config#1]
# Problem/Motivation

It's possible to improve the structure of the configuration

## Proposed changes

It's possible to group components "per-area". 
Example:

```
switches
|-bedroom
   |-switch.bedroom_desk.yaml
   |-switch.bedroom_cupboard.yaml
```

**Comment by frenck** [comment]
Honestly, I've considered that (I might be even visible in the commit history).
Nevertheless, the current size of my system might make that overkill for now.

Therefore, I've chosen to keep it "flatter" until that is actually needed.

**Comment by eliseomartelli** [comment]
Thank-you for inspiring my configuration :) 
https://github.com/eliseomartelli/HA-CONFIG

It's a bit overkill, tho ahah
