### ISSUE TITLE
Updated version

### ISSUE THREAD

**Issue by Ricks88** [frenck/home-assistant-config#123]
Hello!

I was wondering if you maybe did an updated version of your configuration/integration files and folders.
So much has changed in time and i am still using the structure of pointing all integrations to there own folders. 
Also was wondering if  MariaDB or the default DB is used now.

![entities](https://github.com/frenck/home-assistant-config/assets/91467918/e1ea8aeb-dae0-45f1-b4ac-c27772c0590b)
![integrations](https://github.com/frenck/home-assistant-config/assets/91467918/8ac3c760-f5f1-4914-a0ca-45c5469899c6)

Thanks! 
Rick

**Comment by frenck** [comment]
> I was wondering if you maybe did an updated version of your configuration/integration files and folders.

The configuration here is widely outdated from my actual system. However, the principles are still the same.

> Also was wondering if MariaDB or the default DB is used now.

I'm using the default, built-in, SQLite database. MariaDB/MySQL doesn't have much benefit anymore, if anything, it can be even a burden (as it excludes the database from the backup).

../Frenck
