### ISSUE TITLE
File mess - please advice

### ISSUE THREAD

**Issue by madebywitteveen** [frenck/home-assistant-config#127]
# Problem/Motivation

Since the last core update of HA 2024.4 there are problems with the appdeamon and NSPANEL
trying to fix this is resulting in a big mess with the files and where they should be.

can you please provide an extended summary on which location exactly these files should be on the home assistant:

apps.yaml
configuration.yaml
appdeamon.yaml

## Expected behavior

> (What you expected to happen)

## Actual behavior

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by frenck** [comment]
Sorry I don't use those things in my configs. If you need help with using Home Assistant, you should try the community forums or discord chat of the Home Assistant project.

../Frenck

**Comment by madebywitteveen** [comment]
Hello Frenck,

I don't need help with HA, the issue is with the appdaemon ?!
in the appdaemon.yaml file I am trying to point the appdaemon to the new directory with this line:
app_dir: /homeassistant/appdaemon/apps/
But that doesn't work and yes the files are there ?!?
When I remove the app_dir line completely the nspanel starts working again but is using the file in the old directory instead of the new

please advice, thank you

**Comment by madebywitteveen** [comment]
here is the log at starting the daemon:

manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[19:23:52] INFO: Starting AppDaemon...
2024-04-21 19:23:57.464857 INFO AppDaemon: AppDaemon Version 4.4.2 starting
2024-04-21 19:23:57.465191 INFO AppDaemon: Python version is 3.11.6
2024-04-21 19:23:57.465441 INFO AppDaemon: Configuration read from: /config/appdaemon.yaml
2024-04-21 19:23:57.465699 INFO AppDaemon: Added log: AppDaemon
2024-04-21 19:23:57.465853 INFO AppDaemon: Added log: Error
2024-04-21 19:23:57.465985 INFO AppDaemon: Added log: Access
2024-04-21 19:23:57.466226 INFO AppDaemon: Added log: Diag
2024-04-21 19:23:57.742841 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2024-04-21 19:23:58.007459 INFO HASS: HASS Plugin Initializing
2

'config read from /config/appdaemon.yaml' ?? that file is not at that location !?!
appdaemon.yaml is inside addon_configs/a0d7b954_appdaemon

**Comment by madebywitteveen** [comment]
Thank you, but where can I add an issue for appdaemon??
-------- Original message --------From: Franck Nijhof ***@***.***> Date: 21/04/2024  20:18  (GMT+01:00) To: frenck/home-assistant-config ***@***.***> Cc: madebywitteveen ***@***.***>, Author ***@***.***> Subject: Re: [frenck/home-assistant-config] File mess - please advice (Issue #127) 
I don't see how this has anything to do with my configuration. Again, I do not use this stuff at all.

**Comment by frenck** [comment]
The appdaemon project?

**Comment by madebywitteveen** [comment]
Hello,

 

you built this didn’t you? :

**Comment by frenck** [comment]
Nope. And y are commenting on the repository it my Home Assistant configuration of my own personal home, in which I do not use AppDeamon.

I would suggest to consult the documentation of the software you are using on where to go for support.

Thanks

**Comment by madebywitteveen** [comment]
Sorry my mistake 
-------- Original message --------From: Franck Nijhof ***@***.***> Date: 21/04/2024  21:01  (GMT+01:00) To: frenck/home-assistant-config ***@***.***> Cc: madebywitteveen ***@***.***>, Author ***@***.***> Subject: Re: [frenck/home-assistant-config] File mess - please advice (Issue #127) 
Nope. And y are commenting on the repository it my Home Assistant configuration of my own personal home, in which I do not use AppDeamon.
I would suggest to consult the documentation of the software you are using on where to go for support.
Thanks
