### ISSUE TITLE
GUI or yaml?

### ISSUE THREAD

**Issue by Kranzy** [frenck/home-assistant-config#22]
Not an issue, more of a question.

I am looking to follow your config layout and just had a question about if you prefer to use the GUI for what you can or if you prefer to do it in yaml? For example the home location, do you set that in the gui or in your config? Installing integrations (that can be) through HACS or manually? eg zones?

**Comment by frenck** [comment]
For me it is YAML, however, if credentials are involved, I prefer setting up the integration via UI. Fewer credentials in the codebase, the better.

In the case of home location/zones, that is sensitive data, not for GitHub -> UI.

Integrations, I avoid custom integrations in general. HACS is cool, but I simply do not trust custom integrations as there has been no codereview from the HA team.
