### ISSUE TITLE
integration Toon not working

### ISSUE THREAD

**Issue by toudewolbers** [frenck/home-assistant-config#26]
# Problem/Motivation

Users cant login anymore on Toon.

> (Why the issue was filed)

## Expected behavior

Users should login to get toon in HA
> (What you expected to happen)

My toon integrated in HA

## Actual behavior

Users get a error: wrong id/password.

> (What actually happened)

## Steps to reproduce
Goto /integrations/Toon click on Toon. Then you have to input username /password/tenant (for  me eneco) but at least eneco users confirmed it gives a wrong username/password error. (no errors in log).

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)
Would be great this to see working again. And like to donate if it works i really like to integrate my Not rooted toon.

**Comment by frenck** [comment]
This is my personal home configuration...?!

Not sure what this has to do with my home?
