### ISSUE TITLE
Question regarding your configuration

### ISSUE THREAD

**Issue by ceesvanegmond** [frenck/home-assistant-config#27]
Hi Frenck,

Short queston about your configuration. I'm very interested in this setup (files/folders).
In your configuration you reference the `sensor.bathroom_humidity` sensor for example. 
This sensor is also used in some automations (for example the ventilation).

Where do you define this entity? Maybe not in YAML but in UI only? How does this work?
BTW; love your streams!

**Comment by frenck** [comment]
Hey m8!

The `sensor.bathroom_humidity` is provided by the deCONZ integration, which is defined/created in the UI indeed.

../Frenck

**Comment by ceesvanegmond** [comment]
Hi @frenck ,

Thanks for your answer. How do you differentiate what devices/entities you define in YAML, and what UI?

**Comment by frenck** [comment]
I don't differentiate, I use a pretty strict naming. I case about the devices and entities, not how they are added.

What UI? The Home Assistant frontend.

**Comment by ceesvanegmond** [comment]
Yea; I understand the strict naming; which is a good thing. I mean, the ```sensor.bathroom_humidity``` entity is provided by DeConZ right?

In your configuration, some entities are defined within the YAML of this repo; and apparently some entities like ```sensor.bathroom_humidity``` aren't because they are provided by DeConZ.

So my question is more like 'How do you differentiate what entities you define in your config (YAML -> This repo) and what entities are provided by third party apps like DeConZ.,

Thanks!

**Comment by frenck** [comment]
> How do you differentiate what entities you define in your config (YAML -> This repo) and what entities are provided by third party apps like DeConZ.

I don't, because, in the end, it is just one system. Home Assistant provides consolidated devices & entities overviews as well. I can just click on any entity, and see which integration provided that entity from the frontend.
