### ISSUE TITLE
TTS with Google Assistant broke

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#33]
# Problem/Motivation

Somehow my TTS for Google Assistant broke down in 0.109 (I think).

While I do not actively use TTS yet, I do plan on using it. While playing with it just now I noticed it not working.

My Google Assistants are on a different VLAN (IoT), but I have mDNS repeaters set up. Home Assistant does detect them and I am able to control them (e.g., volume, on/off) and see the current status:

![image](https://user-images.githubusercontent.com/195327/80911145-d59eee80-8d34-11ea-92b9-cc1a8e470bf6.png)

Not sure why TTS does not end up with them. Could it be a streaming issue?

Unsure.

**Comment by frenck** [comment]
This is probably caused by the Google Assistant trying to fetch the TTS file from the Home Assistant setup via the set `base_url`. Which it cannot / is not allowed to.

**Comment by timmo001** [comment]
I had the same issue. Turned out it was my base_url was pointing to https instead of http. Definitely likely it's the base URL being wrong

**Comment by frenck** [comment]
My base URL is correct, for other cases, it needs to be this way @timmo001.

However, I've started on re-implementing the way base URL works in HA, so this will probably be resolved soon 😉

**Comment by frenck** [comment]
This should fix it: <https://github.com/home-assistant/core/pull/35224>

**Comment by bonanitech** [comment]
> This should fix it: [home-assistant/core#35224](https://github.com/home-assistant/core/pull/35224)

I can confirm it's working fine with 0.110.1
