### ISSUE TITLE
Finish installation of Xiaomi Curtain rails in Hall

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#35]
# Problem/Motivation

I've recently received a Xiaomi Curtain rail for the hall for testing. General goal: If this works and we like it, to buy more of them in other places around the house.

![image](https://user-images.githubusercontent.com/195327/80913298-f15dc100-8d43-11ea-883c-9ebe3b527c89.png)

Tasks still to do:

- [x] Add a small hook to the right side of the motor, so the curtain can be attached to that. Covering the motor from being visible.
- [x] The device is currently paired to a Xiaomi Gateway in order to get the curtain motor calibrated / aware of the length of the rail. Needs to be unpaired and paired with ZHA.
- [x] Make sure calibration is still OK after repairing on ZHA.
- [ ] Expose the curtains to Google Assistant.
- [ ] Expose the curtains to HomeKit.

Automations:

- [x] Automatically open the curtains at 8:10 every day, except on Saturday 10:00. Sundays or holidays, the curtains will remain closed and not open automatically.
- [x] Automatically close the curtains at 19:00 every day.
- [x] Automatically close when the alarm is armed, do not open when the alarm is armed.
- [ ] If the front doorbell rang and motion is detected in the hallway right after that (e.g., a 1 minute time window) -> Open the curtains.
- [ ] Close curtains if hall occupancy is clear and the curtains should be closed normally at the current time (see above).

Other improvements idea:

- [ ] Add a Xiaomi door sensor to the front door. If the door would be opened from the outside, it can quickly open the curtains. Also, allows preventing the curtains from being closed while the door is open.

**Comment by ronniebee** [comment]
Hi Frenck, having some time around Christmas ( while my wife is watching all you need is love :-) ) I've read your website and love all the things you develop for HA. Real great stuff!  I started using HA last year and really love it. Although some items require some steep learning curves. Maybe a (payed?) HA course ( when Covid is over)  may be a suggestion for all the newbee's like me that have no programming knowledge. I've made my home pretty smart ( lights/alarm/audio/tv/thermostat/> 50 automations, electricity (dsmr)/mqtt stick  etc) but curtains are on my whishlist. I want to use it but my rail isn't straight. It has an 90 degree curved angle at the end. Will this work with this device?  Regards, Ronald.  

And of course I wish you a Merry X-mas!
