### ISSUE TITLE
DIY mod the second desk light

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#37]
# Problem/Motivation

I have two ordinary lights on my desk.
I have modified with an ESP chip running WLED and some LED strips. The other still has the ordinary light bulb in it, controlled with a Z-Wave wall plug.

Tasks:

- [ ] Rebuild the second light to match the first light. Adding an ESP chip and some LED strips.
- [ ] Add the modified light to Home Assistant.
- [ ] Create a light group containing both.

The freed up Z-Wave wallplug can be moved upstairs (hidden somewhere probably) to support the Z-Wave network.

**Comment by frenck** [comment]
Throw out the second light 🗑️ 

So no longer needed :)

**Comment by niro1987** [comment]
![image](https://user-images.githubusercontent.com/7474625/129772018-9160ff2b-7c00-4a7f-b81c-4418906aa9a6.png)

**Comment by frenck** [comment]
hehe a 3d Printer is now in its spot :P
