### ISSUE TITLE
Home Automation ideas collection

### ISSUE THREAD

**Issue by frenck** [frenck/home-assistant-config#47]
# Problem/Motivation

This issue serves as a simple collection for Home Automation ideas/brainfarts:

- Not sure about yet
- Not ready to do yet
- Not yet worthy of its own issue
- A rough idea
- Something picked up somewhere.

## The list

- Start using announcements on my Google devices
- Notifications for washing machine status based on power usage
- Notifications for dryer based on power usage
- Battery monitoring / notifications / alerts
- notification when the Roborock vacuum cleaner needs its dustbin emptied or other maintenance

**Comment by Se7enair** [comment]
- Notifications for washing machine status based on power usage
- Notifications for dryer based on power usage

Definitely do that. It brought my smarthome to a new WAF.
I where inspired by Phil. https://philhawthorne.com/making-dumb-dishwashers-and-washing-machines-smart-alerts-when-the-dishes-and-clothes-are-cleaned/

**Comment by ami6de** [comment]
Idea suggestion: set up user groups in HA. Groups have different access rights. Especially there should be groups which can access lovelace cards „read-only“ and may not modiffy settings just usethe cards as forseen. 

As one use case, imagine a „kids mode“ which allows kids to e.g. execute an automation installed on a lovelace card, but not allow them access to config changes or other modifications, intentionally or not.

thx.
