### ISSUE TITLE
How do you keep your configuration in a subfolder of the repo?

### ISSUE THREAD

**Issue by denysdovhan** [frenck/home-assistant-config#52]
# Problem/Motivation

Most of the configs in Cookbook are just committed `config` folders, so the `config` folder is a repo itself (contains `.git`). The same approach is described in a guide about [sharing configuration on GitHub](https://community.home-assistant.io/t/sharing-your-configuration-on-github/195144).

On another hand, your configuration repo contains the whole configuration in `config` folder of the repo. I suppose you store your repo somewhere else and somehow sync the `/config` folder with a `config` folder in the repo.

How do you do that? How do you keep the configuration in a folder within a repo? How do you sync this config folder with your instance?

Thanks for answer!

**Comment by frenck** [comment]
I've resolved it by bind mounting it into place on the host system. I would not recommend doing or exploring that (unless you have the know-how about that subject already).
