### ISSUE TITLE
How do you have your config folder as a subdirectory in your repo?

### ISSUE THREAD

**Issue by covertbert** [frenck/home-assistant-config#53]
Apologies in advance as I know this probably isn't the right place to be asking this but I've spent ages trying to figure it out and I've asked other people on the forums to no avail...

You have your `config` folder as a subdirectory to the repo but the `git pull` addon will checkout the repo *within* the `config` directory already which means I must have the `configuration.yaml` folder in the root of my repo or I end up with a structure like `/config/config/configuration.yaml`.

How do you get round this? Do you just not use the git pull plugin or is your system setup differently?

**Comment by frenck** [comment]
See `#52`

I do not use the `git_pull` add-on, because I think it is fundamentally not usable in a set up like this.
