### ISSUE TITLE
[Question] Different checkout versions in workflow

### ISSUE THREAD

**Issue by metbril** [frenck/home-assistant-config#59]
Your github workflow uses both checkout v1 and v2. Is this for a specific reason? Why are they different?

https://github.com/frenck/home-assistant-config/blob/96a50b422bf54d8e44ad08a3b49fd90c8881731a/.github/workflows/home-assistant.yml#L17

https://github.com/frenck/home-assistant-config/blob/96a50b422bf54d8e44ad08a3b49fd90c8881731a/.github/workflows/home-assistant.yml#L25

https://github.com/frenck/home-assistant-config/blob/96a50b422bf54d8e44ad08a3b49fd90c8881731a/.github/workflows/home-assistant.yml#L41

**Comment by frenck** [comment]
No, not really, I should add dependabot :D
